---
title:"Inference of Chromosome Selection Parameters and Missegregation Rate in Cancer from DNA-Sequencing Data"
author: "Zijin Xiang, Zhihan Liu, Khanh N. Dinh"
output: html_document
---

# Loading required packages

```{r setup, include=FALSE}
library(CINner)
library(CINner_missegregation_inference)
library(readxl)
library(parallel)
library(pbapply)
```

# Setting for the inference study

The study assumes 50 single-cell and 100 bulk DNA sequencing samples in the data cohort.

```{r}
N_data_sc <- 50
N_data_bulk <- 100
```

We assume that the selection rates in the data are uniformly distributed in [1/1.15, 1.15].

```{r}
bound_ground_truth_arm_s <- 1.15
```

The prior distribution of the selection rate is Uniform[1/1.2, 1.2].

```{r}
bound_ABC_arm_s <- 1.2
```

The missegregation rate is assumed a priori to follow log10(p_misseg) ~ Uniform[-5, -3].

```{r}
bound_ABC_prob_CN_missegregation_left <- -5
bound_ABC_prob_CN_missegregation_right <- -3
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

